- hosts: webserver
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: enabled apache2
      service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_os_family == "Debian"
    - name: enabled httpd
      service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat" 